In [5]:
!pip3 install xgboost

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 MB 5.7 MB/s eta 0:00:0000:0100:01


In [20]:
from xgboost import XGBClassifier
import numpy as np
import pandas as pd
from pathlib import Path
import functools

In [7]:
# read data
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [8]:
data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(data['data'], data['target'], test_size=.2)
# create model instance
bst = XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1, objective='binary:logistic')
# fit model
bst.fit(X_train, y_train)
# make predictions

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=2, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [9]:
preds = bst.predict(X_test)


In [19]:
preds

array([1, 2, 0, 2, 1, 1, 0, 0, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 0, 2, 0, 2,
       1, 2, 0, 2, 1, 0, 0, 0])

In [15]:
data['data'].shape

(150, 4)

In [16]:
data['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [13]:
 data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
 data['target'].shape

(150,)

In [28]:
#loading the data

path1=Path("/home/znazari/machine_learning_ppmi")

data_rna1=pd.read_csv(path1/"ordered_bl_matrix_ir2_count.txt", header=None,index_col=[0] )
data_rna=data_rna1.rename(columns=data_rna1.iloc[0]).drop(data_rna1.index[0]).reset_index(drop=True)

In [30]:
data_predict1=pd.read_csv(path1/"the_diagnosis_count_ir2.txt", header=None ,index_col=[0])
data_predict=data_predict1.rename(columns=data_predict1.iloc[0]).drop(data_predict1.index[0]).reset_index(drop=True)

In [29]:
data_rna

Geneid  10874  12499  12593  13039  13424  14281  14331  \
0      ENSG00000223972.4     10     10     12      7     10      5      7   
1      ENSG00000227232.4    192    418    276    252    292    235    162   
2      ENSG00000243485.2      0      0      2      0      0      0      0   
3      ENSG00000237613.2      0      0      0      0      0      0      0   
4      ENSG00000268020.2      1      0      0      0      0      1      0   
...                  ...    ...    ...    ...    ...    ...    ...    ...   
57815  ENSG00000198695.2    346    142    169    158    138    241     65   
57816  ENSG00000210194.1     48     17     28     24     24     54      3   
57817  ENSG00000198727.2    766   1506    405    379   1316    581    501   
57818  ENSG00000210195.2     62     54     16     67    130     60     63   
57819  ENSG00000210196.2    169    133     65    221    275     95    178   

       14426  15761  ...  59614  60002  60015  60024  60036  60095  60171  \
0          4      4  ...      3      9      9      8     11      2      1   
1        209    128  ...    348    158    205    210    512    211    134   
2          0      0  ...      0      2      0      0      1      1      0   
3          0      0  ...      0      0      0      0      0      0      0   
4          0      1  ...      2      0      0      0      0      0      0   
...      ...    ...  ...    ...    ...    ...    ...    ...    ...    ...   
57815     83    493  ...    258    136     69     86    132     59    142   
57816      7     85  ...     46     25     10     16     13     12     13   
57817    328    517  ...    966    461    498   1049   1260    494    402   
57818     72     62  ...     74     25     48     56     73     34     54   
57819    174    198  ...    289     87     89    204    212     68    103   

       65002  65003  85242  
0          5      6      6  
1        168    235    432  
2          0      0      0  
3          0      0      0  
4          0      0      0  
...      ...    ...    ...  
57815     50     93     92  
57816      5     16      4  
57817    147    872   2501  
57818    117     27     26  
57819    159     94     62  

[57820 rows x 1129 columns]

In [32]:
data_rna_=data_rna.drop(columns='Geneid')

In [40]:
data_rna_1=data_rna_.T
data_rna_1

0      1      2      3      4      5      6      7      8      9      \
10874     10    192      0      0      1      3      0     38      0      3   
12499     10    418      0      0      0      0      0     67      0      0   
12593     12    276      2      0      0      4      3     93      0     10   
13039      7    252      0      0      0      1      0     33      0      2   
13424     10    292      0      0      0      0      0     54      0      2   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
60095      2    211      1      0      0      0      0     57      0      0   
60171      1    134      0      0      0      0      0      6      0      0   
65002      5    168      0      0      0      0      0     20      0      0   
65003      6    235      0      0      0      2      1     71      0      4   
85242      6    432      0      0      0      0      0    141      0      0   

       ...  57810  57811  57812  57813  57814  57815  57816  57817  57818  \
10874  ...    976      2      1      8    511    346     48    766     62   
12499  ...   1577      0      0      0    763    142     17   1506     54   
12593  ...    379      0      0      1    234    169     28    405     16   
13039  ...    440      2      0      1    222    158     24    379     67   
13424  ...   1508      0      1      2   1007    138     24   1316    130   
...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
60095  ...    480      0      1      0    275     59     12    494     34   
60171  ...    474      0      0      1    217    142     13    402     54   
65002  ...    134      0      0      0     86     50      5    147    117   
65003  ...    980      0      0      0    442     93     16    872     27   
85242  ...   2173      0      3      1   1838     92      4   2501     26   

       57819  
10874    169  
12499    133  
12593     65  
13039    221  
13424    275  
...      ...  
60095     68  
60171    103  
65002    159  
65003     94  
85242     62  

[1128 rows x 57820 columns]

In [37]:
data_predict_=data_predict['COHORT_DEFINITION']
data_predict_

0       Parkinson's Disease
1           Healthy Control
2       Parkinson's Disease
3       Parkinson's Disease
4       Parkinson's Disease
               ...         
1123              Prodromal
1124    Parkinson's Disease
1125              Prodromal
1126              Prodromal
1127    Parkinson's Disease
Name: COHORT_DEFINITION, Length: 1128, dtype: object

In [51]:
data_predict['COHORT_DEFINITION'].replace(['Healthy Control', 'Prodromal','SWEDD',"Parkinson's Disease"],
                        [0, 1,2,3], inplace=True)

In [54]:
data1_pred=data_predict['COHORT_DEFINITION']
data1_pred

0       3
1       0
2       3
3       3
4       3
       ..
1123    1
1124    3
1125    1
1126    1
1127    3
Name: COHORT_DEFINITION, Length: 1128, dtype: int64

In [61]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(data_rna_1,data1_pred, test_size=.3)


In [62]:
bst1 = XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1, objective='reg:logistic')


In [63]:
bst1.fit(X_train1, y_train1)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=2, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [64]:
preds1 = bst1.predict(X_test1)


In [65]:
preds1

array([3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 1, 3, 3, 3, 3,
       3, 1, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 1, 3, 3,
       0, 3, 0, 1, 3, 3, 1, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 3, 3,
       3, 3, 3, 3, 3, 1, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 1, 3, 1, 1, 3, 3, 3, 3, 3, 3,
       1, 3, 3, 3, 3, 3, 3, 0, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 0, 3, 1, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 3, 3, 3, 0,
       3, 3, 3, 1, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 1, 3, 1, 3, 1, 0, 3, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 1, 0, 1, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 1, 3, 0,
       3, 3, 3, 1, 3, 3, 1, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1,
       3, 3, 3, 1, 3, 3, 3, 3, 3, 1, 0, 3, 3, 3, 3,

In [66]:
X_test1

0      1      2      3      4      5      6      7      8      9      \
3958      10    139      8      0      0      6      3     49      0     30   
3226       6    321      0      0      0      0      0     70      0      1   
42443     12    263      0      0      0      0      0     37      0      0   
3029       9    236      0      0      0      0      0     61      0      0   
3630       1    196      0      0      0      0      0    107      0      0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
3370       4    185      0      0      0      0      0     42      0      0   
55577      1    148      0      0      0      0      0     40      0      1   
40730      2    183      0      0      0      0      0     48      0      0   
42128      1    132      0      0      0      0      0      3      0      0   
3281      14    136      3      0      5      3      0     21      0     31   

       ...  57810  57811  57812  57813  57814  57815  57816  57817  57818  \
3958   ...    528      5      0      4    513    992    157    528     35   
3226   ...    656      0      0      0    301    164      8    600     97   
42443  ...   1109      0      0      0    509     90     15    933     27   
3029   ...    612      0      0      0    291     68      6    520     71   
3630   ...    618      0      0      0    322     83     13    619     50   
...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
3370   ...    544      0      1      0    337     89      6    577     56   
55577  ...    996      0      0      0    403     82      9    595     51   
40730  ...    921      0      0      0    557    105     15    551    179   
42128  ...    348      0      0      0    197     39      3    349     23   
3281   ...    289      4      0      1    227    311     40    239     18   

       57819  
3958     175  
3226     128  
42443    167  
3029      92  
3630      93  
...      ...  
3370     104  
55577    102  
40730    162  
42128     79  
3281     104  

[339 rows x 57820 columns]